# Run all tests, linters, code analysis and other QA tasks on
# every push to master and PRs.
#
# To SSH into the runner to debug a failure, add the following step before
# the failing step
#       - uses: lhotari/action-upterm@v1
#         with:
#           limit-access-to-actor: true

name: CI

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

# Prevent multiple jobs running after fast subsequent pushes
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:

  test-dts:
    name: Tests DeterminateSystems 1.6

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: DeterminateSystems/nix-installer-action@main
        with:
          modify-profile: true
      - name: force allowUnfree
        run: |
          mkdir -p ~/.config/nixpkgs/
          echo "{ allowUnfree = true; }" > ~/.config/nixpkgs/config.nix
      - name: Install devenv.sh
        run: nix profile install --accept-flake-config github:cachix/devenv/v1.6

      - run: devenv test -d
        env:
          NIXPKGS_ALLOW_UNFREE: 1

  test-cachix:
    name: Tests Cachix 1.6

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v31

      - name: force allowUnfree
        run: |
          mkdir -p ~/.config/nixpkgs/
          echo "{ allowUnfree = true; }" > ~/.config/nixpkgs/config.nix

      - name: Install devenv.sh
        run: nix profile install --accept-flake-config github:cachix/devenv/v1.6

      - run: devenv test -d
        env:
          NIXPKGS_ALLOW_UNFREE: 1
        
  test-dts-14:
    name: Tests DeterminateSystems 1.4

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: DeterminateSystems/nix-installer-action@main
        with:
          modify-profile: true
      - name: force allowUnfree
        run: |
          mkdir -p ~/.config/nixpkgs/
          echo "{ allowUnfree = true; }" > ~/.config/nixpkgs/config.nix
      - name: Install devenv.sh
        run: nix profile install --accept-flake-config github:cachix/devenv/v1.4

      - run: devenv test -d
        env:
          NIXPKGS_ALLOW_UNFREE: 1

  test-cachix-14:
    name: Tests Cachix 1.4

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v31

      - name: force allowUnfree
        run: |
          mkdir -p ~/.config/nixpkgs/
          echo "{ allowUnfree = true; }" > ~/.config/nixpkgs/config.nix
          
      - name: Install devenv.sh
        run: nix profile install --accept-flake-config github:cachix/devenv/v1.4

      - run: devenv test -d
        env:
          NIXPKGS_ALLOW_UNFREE: 1